# Generated by Django 4.2.25 on 2025-12-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_employment_level_and_more'),
        ('applicant', '0007_portfolio'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_match_score',
            field=models.FloatField(blank=True, help_text='0–100 match score from AI', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
        migrations.RemoveField(
            model_name='application',
            name='hired',
        ),
        migrations.RemoveField(
            model_name='application',
            name='shortlisted',
        ),
    ]
