# Generated by Django 4.2.25 on 2025-10-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='internal_note',
            field=models.TextField(blank=True, default='', help_text='Private note for reviewers / owners'),
        ),
    ]
