# Generated by Django 4.2.25 on 2025-12-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_level',
            field=models.CharField(choices=[('unskilled', 'Unskilled / Manual Labor'), ('semi_skilled', 'Semi-skilled / Technical Assistant'), ('skilled', 'Skilled / Trade Professional'), ('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('director', 'Director'), ('professional', 'Professional / White Collar')], default='unskilled', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('unskilled', 'Unskilled / Manual Labor'), ('semi_skilled', 'Semi-skilled / Technical Assistant'), ('skilled', 'Skilled / Trade Professional'), ('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('director', 'Director'), ('professional', 'Professional / White Collar')], max_length=20, null=True),
        ),
    ]
