# Generated by Django 4.2.25 on 2025-12-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='availability',
            field=models.CharField(default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
