# Generated by Django 4.2.25 on 2025-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
