# Generated by Django 4.2.25 on 2025-12-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_jobseeker_avatar_jobseeker_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('language', 'Languages'), ('tools', 'Tools & Software'), ('other', 'Other')], default='technical', max_length=50)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='applicant.jobseeker')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('jobseeker', 'name')},
            },
        ),
    ]
