# Generated by Django 4.2.25 on 2025-12-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
