# Generated by Django 4.2.25 on 2025-12-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_jobseeker_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
